boot.o: boot.S multiboot.h x86_desc.h types.h
wrapper.o: wrapper.S wrapper.h
x86_desc.o: x86_desc.S x86_desc.h types.h
buffer.o: buffer.c buffer.h lib.h types.h keyboard.h wrapper.h rtc.h \
  i8259.h
filesys.o: filesys.c filesys.h types.h lib.h keyboard.h wrapper.h rtc.h
i8259.o: i8259.c i8259.h types.h lib.h
int_handler.o: int_handler.c multiboot.h types.h x86_desc.h lib.h i8259.h \
  debug.h int_handler.h wrapper.h keyboard.h rtc.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  rtc.h wrapper.h int_handler.h paging.h terminal.h keyboard.h buffer.h \
  filesys.h systemcalls.h
keyboard.o: keyboard.c keyboard.h lib.h types.h wrapper.h rtc.h i8259.h \
  buffer.h terminal.h
lib.o: lib.c lib.h types.h buffer.h keyboard.h wrapper.h rtc.h terminal.h
paging.o: paging.c paging.h types.h lib.h
rtc.o: rtc.c rtc.h wrapper.h types.h lib.h i8259.h keyboard.h
systemcalls.o: systemcalls.c systemcalls.h types.h filesys.h wrapper.h \
  paging.h rtc.h terminal.h keyboard.h lib.h buffer.h x86_desc.h
terminal.o: terminal.c terminal.h types.h keyboard.h lib.h wrapper.h \
  rtc.h buffer.h i8259.h
